apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web-app
    project: stock-city
  namespace: stock-city
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80